### PR TITLE
improvements to link roundups meta panels

### PR DESCRIPTION
**Pull request by dryanmedia**
screen shot 2015-06-22 at 9 06 27 am

### CODE REVIEW

**Comment by aschweigert** [comment]
this mostly looks good, is there a reason we're preserving argo-related classnames in the markup/css though? backwards compatibility maybe? or can we go ahead and update those?

**Comment by dryanmedia** [comment]
sure I'll update those this afternoon.

**Comment by aschweigert** [comment]
let's double check for occurrences of "argo-anything" before merging also try to get test coverage for this at least spiked out before merging.

**Comment by dryanmedia** [comment]
Moved into #41 

https://github.com/INN/link-roundups/pull/41

**Pull request closed without merging**
