### PR TITLE
archive template

### PR DESCRIPTION
**Pull request by dryanmedia**
In short, because of how the shortcode uses get_html() (custom func printing the custom field values in rounduplinks) output is always overwritten by admin setting even if custom HTML isn’t in use. it’s difficult to remove title, dash etc for all
instances. Here we add a basic template to handle their display.

CHANGES:
- public css
- inc/saved-links/archive-rounduplink.php added
- inc/saved-links/class-saved-links.php modified to add template

### CODE REVIEW

**Comment by rnagle** [comment]
I think we can dramatically simplify this by changing what `SavedLinks::the_content()` does depending on the context.

So, in `SavedLinks::the_content()` I tried:

```php
	public static function the_content($content) {
		// Only run for argo_links
		global $post;

		if (is_post_type_archive('rounduplink'))
			return get_post_meta($post->ID, 'lr_desc', true);

		if (!isset($post))
			return $content;

		if ( ! ( 'rounduplink' == $post->post_type ) )
			return $content;

		return self::get_html( $post );
	}
```

This being the part to focus on:

```php
...
    if (is_post_type_archive('rounduplink'))
        return get_post_meta($post->ID, 'lr_desc', true);
...
```

Testing this locally produces output like this:

image

**Comment by aschweigert** [comment]
the only thing about this that still seems odd is the byline. For saved links I think you'd probably want to show the source instead of the WP author, but "by: source" doesn't really make sense either...maybe just "source" without the leading "by:"?

**Comment by rnagle** [comment]
@aschweigert I think we can manage that.

**Comment by rnagle** [comment]
So, turns out that we're already dealing with bylines in Link Roundups by using the source field.

Here's a screenshot of the saved links archive page using the Twenty Twelve theme:

image

This doesn't work properly with Largo because it uses custom byline and author link functions that don't apply the default WordPress author and author link filters. This is something that needs to be addressed in Largo core.

**Comment by rnagle** [comment]
Found an [existing issue](https://github.com/INN/Largo/issues/747) in the Largo issue tracker for the byline issues described above.

**Comment by aschweigert** [comment]
Ah, ok. Let's make sure we have a ticket over there and then I think this should be good to close.

**Comment by rnagle** [comment]
Cool. I went ahead and applied my patch to `master` in f8d9651f446cf23337d01138c4c4312be1754f68.

Closing...

**Pull request closed without merging**
