### PR TITLE
grunt and plugin.php

### PR DESCRIPTION
**Pull request by dryanmedia**
- Created plugin.php to handle plugin init
- Grunt
- Less

TO DO: Begin refactor with tests and renaming of files.

### CODE REVIEW

**Comment by aschweigert** [comment]
generally this looks good to me, there's some extra largo-specific stuff in the gruntfile though that should be removed before merging.

**Comment by dryanmedia** [comment]
This pull has some good elements to pull from, but causes ALL the conflicts. 

Once some more pulls are cleaned I'll restart this using this existing branch as a leg up.

**Comment by benlk** [comment]
Might as well take this refactoring opportunity to clean the code:

- [ ] convert all space-based indents in PHP to tabs, and tabs in CSS, LESS, and Js to doublespaces.
- [general WP code formatting guidelines](https://github.com/INN/docs/blob/027a78dcb5e4ff54d95ec60b533ac4d6286ce355/style-guides/code/wordpress.md) - mostly making sure that there are comments for everything

**Comment by dryanmedia** [comment]
#41 has merged this can go as well.

**Pull request closed without merging**
