### PR TITLE
wordpress readme

### PR DESCRIPTION
**Pull request by dryanmedia**
update contributors, updated tested up to, new description short and
long, installation text, FAQ and changelog point at GitHub to save us
steps later on.

### CODE REVIEW

**Comment by dryanmedia** [comment]
In reference to issue #72

**Comment by dryanmedia** [comment]
Note this generator is helpful:
http://generatewp.com/plugin-readme/

**Comment by dryanmedia** [comment]
- [ ] Add header image on svn branch wordpress.org scans to do plugin page header image... yeah.

**Comment by rnagle** [comment]
I'm just going to update the plugin description to fit the 150 character limit on wp dot org until @aschweigert has a chance to review this. I'll also add the image to the svn assets dir.

**Comment by dryanmedia** [comment]
:thumbsup:

**Pull request closed without merging**
